# CONSTRUIR CONTAINER : docker-compose -f docker-compose-dev.yml up --build -d
# DESTRUIR CONTAINER  : docker-compose -f docker-compose-dev.yml down
version: '3.8'

# Services
services:

  # MySQL Database
  db:
    image: mysql:8
    container_name: mysql-camarapp-dev
    restart: unless-stopped    
    volumes:
      - /Users/danielfeitosa/projetos/camarapp/data/mysql:/var/lib/mysql
    expose:
      - 3310
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - network-camarapp-dev

# Networks      
networks: 
  network-camarapp-dev:
    driver: bridge
