
spring:
  datasource:
   url: jdbc:mysql://localhost:3310/sponsorshipDB?useSSL=false&createDatabaseIfNotExist=true
   username: root
   password: password

  jpa:
   show-sql: true
   hibernate:
     ddl-auto: update

